export * from "./User.Interface"
export * from "./ActorProducerInterface"
export * from "./Movie.Interface"
export * from "./Theater.Interface"
export * from "./MovieTime.Interface"
export * from "./Booking.Interface"